"use client";

import { motion } from "framer-motion";
import { Beaker, BookOpen, CheckCircle2, FlaskConical, Info, MoveHorizontal, Sparkles, Triangle, Waves } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { LaboratoryInstrument } from "./laboratory-types";

export function LaboratoryHeader({ title, subject, sessionLabel }: { title: string; subject: string; sessionLabel: string }) {
  return <Card className="overflow-hidden border-primary/20 bg-gradient-to-br from-primary/10 via-card to-secondary/10"><CardContent className="flex flex-col gap-4 p-5 sm:p-7 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-3 flex flex-wrap items-center gap-2"><Badge variant="outline">{subject}</Badge><Badge variant="secondary">{sessionLabel}</Badge></div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">A reusable virtual workbench for guided laboratory practice.</p></div><div className="flex items-center gap-3 rounded-xl border bg-background/70 p-3 text-sm"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><FlaskConical className="h-5 w-5" /></div><div><p className="font-medium">Framework mode</p><p className="text-xs text-muted-foreground">UI-only laboratory workspace</p></div></div></CardContent></Card>;
}

export function InstrumentShelf({ instruments, selectedId, onSelect }: { instruments: LaboratoryInstrument[]; selectedId: string | null; onSelect: (instrument: LaboratoryInstrument) => void }) {
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Beaker className="h-4 w-4 text-primary" />Instrument Shelf</CardTitle><CardDescription>Select equipment to place on the workbench.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-2 xl:grid-cols-3">{instruments.map((instrument) => <button key={instrument.id} type="button" onClick={() => onSelect(instrument)} className={`rounded-lg border p-3 text-left transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:bg-primary/5 ${selectedId === instrument.id ? "border-primary bg-primary/10 ring-2 ring-primary/20" : "bg-background"}`}><instrument.icon className="mb-2 h-5 w-5 text-primary" /><p className="text-xs font-medium">{instrument.name}</p><p className="mt-1 text-[11px] text-muted-foreground">{instrument.category}</p></button>)}</CardContent></Card>;
}

export function Workbench({ selected, onClear }: { selected: LaboratoryInstrument[]; onClear: () => void }) {
  return <Card className="min-h-[25rem]"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>Workbench</CardTitle><CardDescription>Place configured equipment here for the current session.</CardDescription></div><Button variant="ghost" size="sm" onClick={onClear} disabled={selected.length === 0}>Clear</Button></div></CardHeader><CardContent><div className="relative flex min-h-72 flex-wrap content-center justify-center gap-4 overflow-hidden rounded-2xl border border-dashed bg-muted/30 p-6"><div className="pointer-events-none absolute inset-x-8 bottom-6 h-px bg-border" />{selected.length === 0 ? <div className="max-w-xs text-center"><Sparkles className="mx-auto mb-3 h-8 w-8 text-primary/60" /><p className="text-sm font-medium">Your workbench is ready</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Choose an instrument from the shelf to preview its placement.</p></div> : selected.map((instrument, index) => <motion.div key={`${instrument.id}-${index}`} initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }} className="flex h-24 w-24 flex-col items-center justify-center rounded-xl border bg-card p-3 text-center shadow-sm"><instrument.icon className="mb-2 h-8 w-8 text-primary" /><span className="text-[11px] font-medium">{instrument.name}</span></motion.div>)}</div></CardContent></Card>;
}

export function InstructionCard({ instructions }: { instructions: string[] }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><BookOpen className="h-4 w-4 text-primary" />Instruction Panel</CardTitle><CardDescription>Session guidance supplied by configuration.</CardDescription></CardHeader><CardContent className="space-y-3">{instructions.map((instruction, index) => <div key={instruction} className="flex gap-3 rounded-lg border bg-background p-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">{index + 1}</span><p className="text-sm leading-6">{instruction}</p></div>)}</CardContent></Card>; }

export function ChemicalCard({ chemicals }: { chemicals: string[] }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Waves className="h-4 w-4 text-secondary" />Chemical Tray</CardTitle><CardDescription>Configured materials for this workspace.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{chemicals.map((chemical) => <Badge key={chemical} variant="secondary" className="h-auto whitespace-normal px-3 py-1.5">{chemical}</Badge>)}</CardContent></Card>; }

export function SafetyCard() { return <Card className="border-amber-500/30 bg-amber-500/5"><CardHeader><CardTitle className="flex items-center gap-2"><Triangle className="h-4 w-4 text-amber-600" />Safety Card</CardTitle></CardHeader><CardContent className="space-y-2 text-sm leading-6 text-muted-foreground"><p>Wear laboratory protection and keep the workbench clear.</p><p>Use only the equipment and materials configured for the session.</p></CardContent></Card>; }

export function ProgressTracker({ progress }: { progress: number }) { return <Card><CardHeader><CardTitle>Progress Panel</CardTitle><CardDescription>Workspace completion status.</CardDescription></CardHeader><CardContent><div className="mb-2 flex items-center justify-between text-sm"><span>Session progress</span><span className="font-semibold">{progress}%</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs text-muted-foreground"><div><CheckCircle2 className="mx-auto mb-1 h-4 w-4 text-emerald-500" />Prepare</div><div><Info className="mx-auto mb-1 h-4 w-4 text-primary" />Observe</div><div><MoveHorizontal className="mx-auto mb-1 h-4 w-4" />Review</div></div></CardContent></Card>; }

export function EquipmentCard({ instrument }: { instrument: LaboratoryInstrument | null }) { return <Card><CardHeader><CardTitle>Equipment Card</CardTitle></CardHeader><CardContent>{instrument ? <div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary/10 text-primary"><instrument.icon className="h-5 w-5" /></div><div><p className="font-medium">{instrument.name}</p><p className="text-sm text-muted-foreground">{instrument.description}</p></div></div> : <p className="text-sm text-muted-foreground">Select an instrument to view its details.</p>}</CardContent></Card>; }
